<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyProject.DataAccess\MyProject.DataAccess.csproj" />
    <ProjectReference Include="..\MyProject.Entity\MyProject.Entity.csproj" />
  </ItemGroup>

</Project>
